export enum ProductCategory {
  PIZZA_SALGADA = 'SALGADA',
  PIZZA_DOCE = 'DOCE',
  BEBIDA = 'BEBIDA',
  BATATA_FRITA = 'BATATA FRITA',
  COXINHA = 'COXINHA',
  PASTEL = 'PASTEL',
  HAMBURGUER = 'HAMBURGUER',
  ADICIONAL = 'ADICIONAL',
}
